### ISSUE TITLE
Ability to simplify the function call

### ISSUE THREAD

**Issue by venkatb78** [tomSawkins/typed-get-prop#11]
If you guys think this is a good idea, i can start working on the PR

Take the example below
const movie: Movie = {
  title: 'The Matrix',
  year: 1999
  cast: [
    {
      name: 'Keanu Reeves',
      characters: [{
        name: 'Neo'
      }]
    },
    {
      name: 'Carrie-Anne Moss',
      characters: [{
        name: 'Trinity'
      }]
    }
  ]
};

Instead of ``` getProp(movie, 'cast', 1, 'characters', 0, 'name') ```, a user must be able to say 
``` getProp(movie, 'cast[1].characters[0].name') ``` and get back Keanu Reeves or undefined if there is any error/no data

**Comment by codeandcats** [comment]
Hey Venkat, thanks for the feature request. 😄

I'm not sure if Tom has already explained in meatspace yet but the problem with passing multiple properties as a single string is, I believe, it's impossible to know the exact type to return (other than `any`).

This is the trap that every other get prop library on npm has fallen into. By forcing the user to specify properties as separate parameters `typed-get-prop` can return the correct type every time.

**Comment by venkatb78** [comment]
Thanks for the explanation mate

I will close the request then
